framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            users:
                dsn: "%env(MESSENGER_TRANSPORT_DSN_USERS)%"
                options:
                    queues:
                        users: ~
            locations:
                dsn: "%env(MESSENGER_TRANSPORT_DSN_LOCATIONS)%"
                options:
                    queues:
                        locations: ~

        routing:
            # Route your messages to the transports
            'App\Message\UpdateUser': users
            'App\Message\GetLocation': locations
