version: '3.7'

services:
    mysql:
        container_name: 'git-stars_mysql'
        hostname: 'git-stars_mysql'
        image: 'mysql:5.7'
        ports: 
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
    rabbitmq:
        container_name: 'git-stars_rabbitmq'
        hostname: 'git-stars_rabbitmq'
        image: 'rabbitmq:3.8-management-alpine'
        ports:
            - '15672:15672'
            - '5672:5672'
